version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: alex_koin:latest
    env_file: .env
    environment:
      - DATABASE_URL=postgres://db:5432/akc
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11.12
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
