version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: alex_koin:latest
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/akc
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11.12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

volumes:
  postgres-data:
